### ISSUE TITLE
Add a better looking url input 

### ISSUE THREAD

**Issue by chrislaughlin** [chrislaughlin/floppy-bundle#2]
Add something better looking than below, free-range on how it looks but please use CSS and add no new deps 

![image](https://user-images.githubusercontent.com/495517/94848399-db038080-041b-11eb-9686-c948bc52b043.png)

**Comment by i-aryan** [comment]
Hey, I'll make it good for you. Assign it, please @chrislaughlin

**Comment by chrislaughlin** [comment]
It's all yours, thanks

**Comment by i-aryan** [comment]
Hey @chrislaughlin I made a PR. Review it please, thanks.

**Comment by chrislaughlin** [comment]
Thanks
